### ISSUE TITLE
docker-compose com proxy reverso configurado e ssl

### ISSUE THREAD

**Issue by guilhermesgit** [ticketz-oss/ticketz#100]
**Is your feature request related to a problem? Please describe.**
Ao subir  a aplicação exige do  usuário o conhecimento de infra, com o traefik configurado com docker-compose e os ips apontando pro subdomínio é somente digitar docker-compose -f file -d e a solução está pronta com ssl.

**Describe the solution you'd like**
O traefik é um proxy reverso onde é possível utilizar o docker-compose junto a aplicação sem a necessitade de se preocupar com renovação do certbot do letsencrypt.

**Describe alternatives you've considered**
Não necessita a utilização de certboot e nem nginx como proxy reverso, o traefik faz todo trabalho e renova ssl automaticamente não necessitando ao usuário se preocupar com renovação do ssl.

**Comment by allgood** [comment]
o nginx está sendo usado como proxy reverso na configuração dos docker comopse, gerando certificados e ajustando tudo através do comando incluído no README. O comando foi feito exatamente para que não seja necessário nenhuma informação sobre infra, ele inclusive cuida da instalação do docker.

o traefik eu não conheço.

dito isso, o projeto se concentra principalmente na criação dos containers backend e frontend sendo que eles podem ser usados das mais diversas maneiras.

Você pode contribuir com um guia ou pull requests que adicionam essa alternativa.
