### ISSUE TITLE
Usuário não admin sem permissão para ver grupo

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#104]
Ao habilitar a opção de grupo os usuários não admin, não conseguem ver as mensagens.

**Erro que exibe**
![image](https://github.com/ticketz-oss/ticketz/assets/66420271/79da9136-11e6-434e-ae18-9686b127ce8e)

Outros erros, porem não sei se tem correlação

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/9a58bb17-5128-469e-ba6f-fdae22b124bf)

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/0bcd1aeb-5b84-4df3-abe7-2ab9bf02290b)

**Comment by allgood** [comment]
o ticketz não tem suporte avançado a grupos atualmente. grupos são tratados como um contato, o ticket do grupo pode ser encaminhado para uma fila e deve ser atendido por um usuário. opções para melhor suporte a grupo podem ser pensadas no futuro, porém grupos são muito custosos no processamento da baileys e costumam causar problemas.
