### ISSUE TITLE
Falha ao receber mensagens efêmeras enviadas pelo Whatsapp Desktop for Windows

### ISSUE THREAD

**Issue by cleitonme** [ticketz-oss/ticketz#11]
ao enviar mensagem pelo aplicativo windows "https://apps.microsoft.com/detail/9nksqgp7f2nh?hl=pt-br&gl=BR" para numero cadastrado no ticketz-oss ele nao recebe a mensagem... nao responde...

se enviar usando mesmo numero pelo aplicativo instalado no windows ou pelo web.whatsapp.com funciona normalmente, entao nao eh problema da instalacao... instalado ubuntu 22 usando docker

**Comment by rodsmar** [comment]
Comigo funciona normalmente. Sua instalação é feita via IP público/VPS ou rede local?

**Comment by cleitonme** [comment]
ip publico... mas usando esse aplicativo ? https://apps.microsoft.com/detail/9nksqgp7f2nh?hl=pt-br&gl=BR

**Comment by rodsmar** [comment]
> ip publico... mas usando esse aplicativo ? https://apps.microsoft.com/detail/9nksqgp7f2nh?hl=pt-br&gl=BR

Eu me refiro ao ticketz.

**Comment by cleitonme** [comment]
sim to falando ticketz quando se envia mensagem "usando aplicativo do windows" para numero cadastrado na plataforma ela nao recebe a mensagem

**Comment by allgood** [comment]
se entendi bem é o Whatsapp Desktop para windows (nem sabia que existia)... eu não tenho como testar isso aqui, se alguém puder me ajudar a debugar, me avise.

**Comment by cleitonme** [comment]
Posso te ajudar.. você não usa windows? se usa so baixar na microsoft store, tipo whatsweb so que tem mais recursos

**Comment by allgood** [comment]
@cleitonme Não uso windows. Me chame no 49999812291 para combinar como você consegue me ajudar a debugar isso. Obrigado.

**Comment by allgood** [comment]
Identificada a falha, é em razão das mensagens efêmeras ativadas (auto-apagantes depois de um tempo).

**Comment by allgood** [comment]
A falha parece ocorrer apenas quando a mensagem é enviada pelo aplicativo windows.
