### ISSUE TITLE
Acesso a VPS por meio de Aapanel

### ISSUE THREAD

**Issue by trinityrrocha** [ticketz-oss/ticketz#110]
#requisito

Ajustar o escript de instalação rápida para que seja incluído mais um URL para que seja incluído na cadeia de certificados, exemplo;

curl -sSL get.ticke.tz | sudo bash -s backend.example.com frontend.example.com name@example.com Aapanel.example.com

#nalise
isso servirá para acessibilidade ao servidor para realização de manutenções, instalações de ferramentas como google backup, Cron com notificação, Terminal via web e outros, o mesmo oferece diversos recursos gratuitos muitos bons que pode ajudar no dia a dia de quem não tem tanta familiaridade com Linux.

![Aapanel 5](https://github.com/ticketz-oss/ticketz/assets/136651958/4690d464-620e-460d-ac97-ef2286caf256)
![Aapanel 4](https://github.com/ticketz-oss/ticketz/assets/136651958/53d24c5f-4c19-44a4-bce2-9c2d6d7a33e8)
![Aapanel 2](https://github.com/ticketz-oss/ticketz/assets/136651958/b244553d-4831-450e-9dee-964d736c0044)
![Aapanel 3](https://github.com/ticketz-oss/ticketz/assets/136651958/cf7e9683-7133-4be5-8fe8-0e5bbdf33961)
![Aapainel1](https://github.com/ticketz-oss/ticketz/assets/136651958/53ed126d-583d-4ec1-8a39-297a9fe114df)

**Comment by allgood** [comment]
qualquer alteração para instalar além do básico do ticketz deve ser feita manualmente, essas ações vão além do escopo do projeto.
