### ISSUE TITLE
Lista de arquivos permitidos

### ISSUE THREAD

**Issue by trinityrrocha** [ticketz-oss/ticketz#114]
Ter opção do Administrador Geral configurar uma lista de extensão e tamanho de arquivos que serão permitidos enviar através do chat, como por exemplo proibir o envio de arquivos com a extensão ".exe, .msi, .bat, vbs etc" e determinar o tamanho de arquivos que serão enviados, que por muitas vezes o usuário pode enviar um vídeo de 1Gb e acabar consumindo muito os recursos do servidor e causando lentidão.

**Comment by allgood** [comment]
Uma lista de arquivos permitidos pode causar um "inferno administrativo" pois vários casos podem ocorrer e acaba ocasionando um suporte desnecessário.

Minha opinião é que esse tipo de filtragem é escopo de outra ferramenta (antivirus).

Com relação ao tamanho concordo que um limite no frontend pode ajudar a evitar problemas com o backend - favor abrir outra issue para esse objetivo.
