### ISSUE TITLE
Poder Definir o Idioma Padrão Para todo sistema

### ISSUE THREAD

**Issue by trinityrrocha** [ticketz-oss/ticketz#116]
Permitir que o Super Admin defina qual será o Idioma padrão para todo o sistema, dessa forma os clientes que entraram pela primeira vez não vai necessitar definir o idioma já que o serviço será disponibilizado para todo o mundo, porém o Super Admin dificilmente será do seu publico local.
No meu caso irei trabalhar comente com Brasileiros, então será definido Português Brasil.

**Comment by allgood** [comment]
A ideia é detectar o idioma padrão do navegador de forma que não precise selecionar. Mesmo em uma empresa podem haver funcionários de diferentes línguas então é importante deixar flexível. A seleção pela língua do navegador me parece ser a melhor.
