### ISSUE TITLE
Label fica sobre a mensagem

### ISSUE THREAD

**Issue by wecloud1** [ticketz-oss/ticketz#121]
Em algumas partes de sistema o label fica sobre a caixa de texto
![image](https://github.com/user-attachments/assets/81020566-ffc9-43a8-b524-ae3816869cda)
Nesse caso, quando clica na caixa de texto o label fica no lugar correto
![image](https://github.com/user-attachments/assets/6e64f576-de04-405e-844e-cfd7e70b71d4)
mas ao clicar fora da caixa, ele fica sobre a caixa de texto
![image](https://github.com/user-attachments/assets/5118441e-fa84-427a-9078-e51865fa840e)
Já na pagina de horário de atendimento, o label fica sempre sobre o texto

**Comment by allgood** [comment]
Estou corrigindo a colisão na tela de filas, porém isso pode aparecer em diversos pontos do sistema.

a tela dos horários não tem muito o que fazer porque as strings são grandes
