### ISSUE TITLE
Horário de expediente por fila não está funcionando

### ISSUE THREAD

**Issue by wecloud1** [ticketz-oss/ticketz#123]
![image](https://github.com/user-attachments/assets/21ab658e-fe72-4227-b23f-faff6f317399)
![image](https://github.com/user-attachments/assets/e1bea53f-af0d-49c3-8f2a-1fc72832aefd)

Criei um horário de atendimento por fila, para a fila "Filial 1", mas ele não está funcionando
![image](https://github.com/user-attachments/assets/a3cd0d7b-eec4-4ee9-849f-3cb9367167ea)
Continua respondendo normalmente, não aparece a mensagem de Fora de expediente

**Comment by allgood** [comment]
duplicado de #48
