### ISSUE TITLE
Download de Foto | PDF Não funciona

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#124]
Quando recebemos um arquivo pelo ticketz o mesmo esta abrindo em outra guia a imagem ou pdf antes de fazer download.

![image](https://github.com/user-attachments/assets/a2414401-dd54-4eab-a44c-33d736bcc470)

**Comment by allgood** [comment]
Marquei tanto como bug quanto como melhoria, porque acredito que o ideal é ter dois botões caso o arquivo seja visualizável no navegador. Um para ver e outro para baixar.
