### ISSUE TITLE
problema de resposta ao fechar ticket

### ISSUE THREAD

**Issue by ryanreche** [ticketz-oss/ticketz#126]
ao fechar e enviar a mensagem automatica, vai sem os parametros informad, abaixo segue o exemplo

como esta configurado
![image](https://github.com/user-attachments/assets/74e4deac-4719-4dab-a026-ee212868d64e)
como chega para o usuario
![image](https://github.com/user-attachments/assets/198bd0ba-eb87-4d39-9240-99badc4389f6)

mensagem

"*_‎‎Mensagem Automática_*"

Seu atendimento foi encerrado, por gentileza não responda esta mensagem.

**Comment by allgood** [comment]
Não consegui simular esse erro aqui, operou certinho.

![image](https://github.com/user-attachments/assets/1f4b8f51-6921-42dd-a1b8-901c564b8133)
