### ISSUE TITLE
Sistema emperra com arquivos grandes

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#130]
Verifiquei que quando recebemos anexos | vídeos grandes em MB o sistema trava e é necessário reiniciar o backend.

**Comment by allgood** [comment]
acontece por conta da forma como o nodejs trabalha, um download grande acaba monopolizando o processamento.

**Comment by allgood** [comment]
devo colocar um limitador de tamanho para arquivos recebidos de forma a evitar o problema.
