### ISSUE TITLE
Mensagem em uma imagem marcada nao aparece, aparece somente a imagem, porem a mensagem que foi digitada em cima de uma imagem nao aparece.

### ISSUE THREAD

**Issue by djwesleyborges** [ticketz-oss/ticketz#132]
No celular a mensagem teste aparece.
![WhatsApp Image 2024-07-30 at 18 51 16](https://github.com/user-attachments/assets/deefc627-661d-4d5b-8420-6307557e6712)

No sistema a mensagem **teste** não aparece
![image](https://github.com/user-attachments/assets/6f0fac71-8ac1-45fa-a81c-67253fccdc27)

**Comment by allgood** [comment]
Testei aqui e funcionou normal. Talvez eu tenha arrumado antes, favor confirmar ou detalhar melhor como simular o problema.

Como foi enviado pelo whatsapp web
![image](https://github.com/user-attachments/assets/396b0ac7-1899-4f04-89ff-91aea19781ea)

Como chegou no Ticketz
![image](https://github.com/user-attachments/assets/a7fd5938-7d05-47bf-9cf7-4a233a13f8ba)
