### ISSUE TITLE
Non Docker Instalation

### ISSUE THREAD

**Issue by rspersahabatan** [ticketz-oss/ticketz#138]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by allgood** [comment]
You can install Ticketz Open Source without docker.

*Backend:* you will need to provide postgres and redis configuration on a .env file for backend and run it using nodejs. It is important to setup an internal port.

*Frontend:* you will need to build the code and publish it using a webserver. You will need to configure your webserver to forward "/backend" and "/socket-io" addresses to the port of the backend. You will also need to setup a file on the root of the webserver named `config.json` using the following format:

```json
{
  "BACKEND_PROTOCOL": "https",
  "BACKEND_HOST": "frontend.example.com",
  "BACKEND_PATH": "/backend",
  "BACKEND_PORT": "443",
}
```

All of this are done from the docker setup in a way to guarantee that the system is running within the specification, I recommend to use docker, if you need to use an external Postgres or Redis intallation, or want to change the exposure of the webserver you can run docker only with the backend and frontend containers.

Anyway if you really need to run it outside docker I recommend you inspect the docker config files to see how it joins the pieces together. (nginx-proxy, acme-companion, postgres and redis with the backend and frontend containers).
