### ISSUE TITLE
Foco de entrada ao responder mensagem

### ISSUE THREAD

**Issue by joaopaulosobral** [ticketz-oss/ticketz#141]
Ao responder mensagem o cursor sai do campo de digitação, é preciso clicar novamente para abrir o campo para digitar. 
Acaba dificultando ao atendimento.

**Comment by motheks** [comment]
Interessante ter um print ou até mesmo um gif para @allgood conseguir começar a verificar.

**Comment by joaopaulosobral** [comment]
![responder ticketz1](https://github.com/user-attachments/assets/2c1807a5-b07d-4b69-b138-7ead1ba7a042)
![responder ticketz2](https://github.com/user-attachments/assets/c402204a-a227-4e91-be77-1708c8414943)

Quando clicamos responder uma mensagem, ele seleciona, mas na aba de responder não fica selecionado para digitar, as vezes digitamos e quando percebemos é em vão. 
É preciso selecionar com o mouse e digitar a resposta, de uma forma perde um tempo para muitos atendimentos.
