### ISSUE TITLE
Erro em conexões com mesmo nome de empresas

### ISSUE THREAD

**Issue by leostrong84** [ticketz-oss/ticketz#142]
Está dando erro de conexão com mesmo nome de empresas diferentes, informa que já existe a conexão.

![Captura de tela 2024-08-22 154727](https://github.com/user-attachments/assets/86f49711-0e51-4f7a-b2b9-4be75e2f4aa1)

**Comment by motheks** [comment]
Poderia apresentar mais prints, e a que nomes existentes ?
