### ISSUE TITLE
Opção de responder não está funcionando corretamente

### ISSUE THREAD

**Issue by diegojuvino** [ticketz-oss/ticketz#146]
![image](https://github.com/user-attachments/assets/ecf0ed56-0066-441d-88dc-15a0e9bb7fa5)

Vi que ao usar a opção de responder mensagem pelo ticketz, a mesma não aparece como resposta quando olhado pelo aplicativo do whatsapp no celular

**Comment by allgood** [comment]
![image](https://github.com/user-attachments/assets/7f7c58f0-7e9b-423f-9751-e6be75cb4017)

Conferi aqui, tá aparecendo assim. Vou ver se resolvo

**Comment by allgood** [comment]
@diegojuvino , não consegui simular aqui, consegue ver se ocorre com a versão mais recente? se puder informar melhor como simular o problema também ajuda.

**Comment by allgood** [comment]
corrigido! encontrei os problemas!
