### ISSUE TITLE
Erro com nomes das conecções

### ISSUE THREAD

**Issue by diegojuvino** [ticketz-oss/ticketz#148]
![image](https://github.com/user-attachments/assets/0d303f40-2b04-44bc-9feb-ed20b82484e1)

Se uma empresa cadastra uma conexão com um nome e uma outra cadastra a conexão com o mesmo nome, o sistema recusa, mesmo sendo empresas diferentes, retorna uma mensagem de erro informando que já existe uma conexão cadastrada.

**Comment by allgood** [comment]
duplicado do #142
