### ISSUE TITLE
Ajuste de cores do Chat Interno

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#151]
Seria importante ajustar as cores, para ter uma visualização melhor do que esta sendo escrito.

![image](https://github.com/user-attachments/assets/6fba9dde-966c-4639-b18c-177ae0f394cf)

**Comment by allgood** [comment]
Corrigido no Ticketz PRO
![image](https://github.com/user-attachments/assets/5035322d-4bb9-4475-91c8-9cc0d74081db)
