### ISSUE TITLE
Banco de dados

### ISSUE THREAD

**Issue by felipeortiz21** [ticketz-oss/ticketz#158]
Olá, precisava pegar um relatório no de avaliações (quantidade de avaliação)
porem nao consigo acessar o banco de dados 
o banco e o postgres ? teria alguma forma de acessar ele externo ?

**Comment by allgood** [comment]
A configuração padrão utilizando docker não expõe as portas de redis e postgres, por razões de segurança.

É possível acessar o banco de dados adicionando um container com o pgadmin.
