### ISSUE TITLE
Endpoint IXC

### ISSUE THREAD

**Issue by rapososoftwares** [ticketz-oss/ticketz#168]
A idéia é um endpoint para receber e processar as mensagens enviadas pelo IXC Provedor.
Onde consigamos definir o delay que cada mensagem será processada na fila.

**Comment by allgood** [comment]
@rapososoftwares , você diz o envio de notificações por parte do IXC?

Se for isso, já está implementado na versão PRO, bastando utilizar o mesmo protocolo do Gammu. Nesse recurso a mensagem é enfileirada mas enviada imediatamente.
