### ISSUE TITLE
Bug na funcionalidade de Visualização (Olho Azul) marcando mensagem como lida

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#176]
**Descrição do Problema:**

Ao clicar na opção **"Visualizar"** (ícone do olho azul) em um ticket, a mensagem está sendo automaticamente marcada como "lida". No entanto, essa funcionalidade deveria permitir apenas uma visualização prévia do ticket, sem marcar a mensagem como lida, já que essa ação não reflete a intenção do usuário de pegar ou interagir diretamente com o ticket.

**Comportamento Esperado:**

Ao utilizar a opção **"Visualizar"** (olho azul), o sistema não deve marcar o ticket como lido, pois trata-se apenas de uma verificação rápida. O ticket só deveria ser marcado como lido quando o usuário realizar uma ação de interação, como clicar para responder ou pegar o ticket.

**Passos para Reproduzir:**

1. Acessar a lista de tickets no Ticketz.
2. Clicar no ícone de "Visualizar" (olho azul) ao lado de um ticket.
3. Notar que o ticket é marcado como "lido" imediatamente após essa ação, sem o usuário ter efetivamente interagido ou pego o ticket.
4. Impacto: Esse comportamento pode causar confusão e problemas de gerenciamento, pois marca tickets como lidos antes que o usuário tenha a intenção de interagir ou responder.

**Comment by motheks** [comment]
Problema resolvido na versão Ticketz PRO v0.99.41

**Comment by allgood** [comment]
Resolvido com o commit 52a7c55
