### ISSUE TITLE
Support for arm architeture

### ISSUE THREAD

**Issue by renansteles** [ticketz-oss/ticketz#18]
**Is your feature request related to a problem? Please describe.**
Problem on build using RaspberryPi 4 with arm architeture

**Describe the solution you'd like**
Please, create a option compatible with arm architeture.

I`m trying to run ticketz on RaspberryPi 4 and when I try to build the error appear:
"exec /usr/bin/dumb-ini: exec format error"

**Comment by allgood** [comment]
I believe that Rapsberry doesn't have the power needed to build the code.  Also don't know if it is possible to use docker, postgres and redis on a Raspberry.

For now this will not be supported. If anybody have a contribution in this direction I will evaluate and merge.
