### ISSUE TITLE
Bug - Falta de Assinatura do Atendente ao Enviar Foto com Texto

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#182]
**Descrição do Problema:**

Identificamos um problema no sistema Ticketz relacionado ao envio de fotos com texto. Quando o atendente envia uma mensagem contendo uma foto acompanhada de texto, a assinatura do atendente não é exibida junto à mensagem, diferentemente das mensagens de texto puro.

**Comportamento Esperado:**

Ao enviar uma foto com texto, a assinatura do atendente (nome e/ou cargo) deveria ser exibida junto à mensagem, assim como acontece nas mensagens de texto.
Comportamento Atual:

Quando uma mensagem contém uma foto e texto, a assinatura do atendente não aparece na mensagem enviada, o que pode causar falta de identificação para o cliente.

![image](https://github.com/user-attachments/assets/76584477-c50c-4dca-b8ea-b71a5cafda71)

**Impacto do Problema:**

Falta de Identificação do Atendente: Os clientes podem não saber quem está enviando a mensagem, especialmente em casos em que mais de um atendente participa do atendimento.
Dificuldade de Rastreamento: Pode dificultar a análise de histórico de atendimentos e identificar qual atendente enviou a mensagem.
Percepção Profissional: A ausência da assinatura pode dar a impressão de que o atendimento não está seguindo os padrões de personalização.

**Passos para Reproduzir:**

**1.** Um atendente envia uma mensagem que contém uma foto e um texto.
**2.** A mensagem é recebida pelo cliente sem a assinatura do atendente.
**3.** Verifica-se que a assinatura só aparece em mensagens de texto puro, mas não em mensagens que incluem imagens.
**4.** Solicitação de Correção: Gostaríamos de solicitar a análise e correção desse problema para garantir que a assinatura do atendente seja exibida em todas as mensagens, independentemente do tipo de conteúdo.

**Comment by allgood** [comment]
Corrigido na PRO
