### ISSUE TITLE
Tela Branca em tickets com ligação telefônica

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#19]
Estamos enfrentando alguns problemas em em alguns tickets aonde ao clicar em algumas conversas o sistema fica com tela branca, segue print abaixo.:

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/0f891b7c-81c9-48a8-ad36-90230cd9989c)

Erro Console

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/dbdec71a-8902-44e4-a63a-0adb3f1921f8)

Caso precise de algum acesso para verificar o bug pode me chamar no 17 9 88042950

**Comment by renansteles** [comment]
Está acontecendo mesmo problema comigo e, pelo o que notei, acontece quando há chamada de VOZ ou de VIDEO no ticket.

**Comment by motheks** [comment]
Realmente o @renansteles esta certo, somente tickets que tem ligação que a tela fica branca
