### ISSUE TITLE
Após atualização, as mensagens fora de horário comercial vão para fila cinza

### ISSUE THREAD

**Issue by ettobr** [ticketz-oss/ticketz#193]
Após atualização, as mensagens fora de horário comercial vão para fila cinza, trabalho com uma única fila chamada Vendas, tenho nela o horário de atendimento, não uso (bot), na conexão está vinculada essa única fila.

**Comment by joaopaulosobral** [comment]
Percebi o meu também está assim. Fica sem fila...

**Comment by allgood** [comment]
Commit c02f28d adicionou a opção para configurar se ao receber uma mensagem fora do horário se o atendimento deve ser deixado como pendente ou fechado.
