### ISSUE TITLE
English(en.js) format is not woking as Pt.js

### ISSUE THREAD

**Issue by tyuhbh0** [ticketz-oss/ticketz#2]
**Describe the bug**
I have tried to change pt.js to en.js but not working.. 

**To Reproduce**
1. Run cammand "nano frontend/src/translate/i18n.js"
2. Change "pt" to "en"
3. Restart Frontend
4. Not made any changes.

**Expected behavior**
Should be change as en.js

**Desktop (please complete the following information):**
- Docker
- chrome browser

**Additional context**
i have made en.js to pt.js & pt.js to en.js but still not work.

**Comment by allgood** [comment]
The files should not be swapped. If you need to make english the default language, for now you must change the code.
