### ISSUE TITLE
atendimento sem fila

### ISSUE THREAD

**Issue by renan-delgado** [ticketz-oss/ticketz#20]
![image](https://github.com/ticketz-oss/ticketz/assets/127997362/4ad3d81f-a72b-4b64-bfd5-c5a7aef6ac82)
 existe alguma modificação que eu possa fazer para que  seja possivel habilitar a função para que atendentes consigam ver atendimento sem fila!?

**Comment by allgood** [comment]
A princípio atendimento sem fila apenas pelo Admin. 

Razão: existe uma segmentação das emissões de evento para usuários participantes das filas, um contato "não familiarizado" com atendimento automatizado pode acabar enviando informações que não devem ser vistas por qualquer pessoa, portanto um admin deve decidir para qual fila encaminhar.

Como "workaroud" o ideal é fazer uma fila padrão e identificar usuários que estarão aptos a atender estes casos. Aí é da decisão do administrador se vai deixar apenas alguns usuários com nível mais alto observarem ou não.
