### ISSUE TITLE
Mensagem de Avaliação

### ISSUE THREAD

**Issue by leonardooliveira64** [ticketz-oss/ticketz#204]
A mensagem de avaliação precisa ser corrigida, discriminar as opções que o fonte ja entrega, ou respeitar a msg que é escrita pelo admin.

**Comment by allgood** [comment]
Foi alterado para nota de 1 a 5 sem descrição de cada opção. Não vejo necessidade de alterar o texto que pede a nota porém entendo que é preciso internacionalizar ele.
