### ISSUE TITLE
Acrescentar opção para direcionar ticket a uma fila

### ISSUE THREAD

**Issue by leonardooliveira64** [ticketz-oss/ticketz#205]
Ao abrir o ticket e o usuário não escolher uma fila, o ticket fica "sem fila" ficando visivel apenas para o admin...
poderia ser feito um direcionamento de fila, por um tempo determinado, caso o usuário não escolha a fila, ja direciona automaticamente.
ou depois de um tempo, envia outra mensagem para o usuario escolher uma opção.

**Comment by allgood** [comment]
A função de timeout para tickets sem fila jé é disponível na versão PRO
