### ISSUE TITLE
Messages to WhatsApp groups

### ISSUE THREAD

**Issue by orcapa** [ticketz-oss/ticketz#21]
Is it possible to send messages to groups through 120363146269777398@g.us ?

**Comment by allgood** [comment]
It works with groups. Some old groups have a known bug to be fixed soon

**Comment by orcapa** [comment]
hello @allgood how can i send this by API. ?  Currently I sent the message via API but just give me the phone number. 

{ "number": "573148814322", "body": "Sua mensagem" }

I need change number  to groub ID  :  120363146269777398@g.us
