### ISSUE TITLE
mensagem apagada não mostra autor - falha aleatória

### ISSUE THREAD

**Issue by rapososoftwares** [ticketz-oss/ticketz#213]
Quando o outro lado envia uma mensagem em grupo e apaga, o nome da pessoa que enviou não aparece.

![image](https://github.com/user-attachments/assets/6d4719b0-797b-4e75-88af-a934fa52296c)

ja no whatsapp

![image](https://github.com/user-attachments/assets/bd2c90bb-dcf1-4428-9698-f0835ff8233a)

**Comment by allgood** [comment]
acabei de testar aqui e está mostrando certinho, consegue dar mais detalhes?

![image](https://github.com/user-attachments/assets/6580d620-228e-4dc5-a5a2-b808d8b92b46)

**Comment by rapososoftwares** [comment]
![image](https://github.com/user-attachments/assets/ed251ad7-d6db-4dd7-9645-8849962f214c)

**Comment by rapososoftwares** [comment]
![image](https://github.com/user-attachments/assets/3ed2e984-0738-4497-b01c-8f4ea2df740b)

![image](https://github.com/user-attachments/assets/3c90e0a9-e8be-4e7d-8d75-d1a8053a7f84)


v1.0.21 / 2024-10-30T15:15:00Z

**Comment by allgood** [comment]
Antes de apagar tá mostrando certo? O Ticketz não usa os contatos do celular, ele usa o cadastro de contatos próprio.

**Comment by rapososoftwares** [comment]
Sim, aparece normal o nome do contato antes dele apagar, ai quando apaga fica sem os dados ali do contato conforme as prints

**Comment by allgood** [comment]
não estou conseguindo simular esse problema aqui, sempre funciona! é preciso identificar qual peculiaridade causa a perda do contato

**Comment by allgood** [comment]
identifiquei... o problema ocorre ao receber a exclusão de uma mensagem que havia anteriormente sido editada. E o problema é momentâneo, após f5 normaliza.

**Comment by allgood** [comment]
![image](https://github.com/user-attachments/assets/9b3d27f2-26bd-41d7-a246-ffe8e20fee7c)

não é nem isso... estas 5 mensagens foram apagadas de uma vez só!

**Comment by allgood** [comment]
possivelmente vem dois eventos e a ordem está invertendo.
