### ISSUE TITLE
Erro na fila após atualização

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#22]
**Sempre que atualizo a versao do sistema ocorre esse erro**

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/069a1f7b-7c75-4cb2-8246-9aeace4f3851)

**Erro no console**

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/5a4ec3a6-7f19-4000-a78e-553a6f3a9dab)

**Comando que utilizo para atualizar**

docker compose -f docker-compose-acme.yaml down
git stash
git pull
git stash pop
docker compose -f docker-compose-acme.yaml up -d --build

**Comment by AlvaroBrasilia** [comment]
Eu enfrentei esse erro ontem quando fiz a minha primeira instalação, acredito que o erro esteja relacionado a atualização da semana passada onde os parâmetros são convertidos de `string` para `number`, mas ocorre que `queueOptionId` aparentemente nunca é enviado e então cai no `if` logo abaixo como `NaN`.

Linda mencionada:

https://github.com/ticketz-oss/ticketz/blob/c3b4fd1b17cf0e4bfe0187e585d5b2d34cce17ac/backend/src/controllers/QueueOptionController.ts#L26

Paliativamente eu contornei esse erro apenas atribuindo um valor padrão `0` para `queueOptionId` na linha 22 .

Alterando de: 

`const { queueId, queueOptionId, parentId } = req.query as FilterList;`

Para:

`const { queueId, queueOptionId = 0, parentId } = req.query as FilterList;`

**Comment by allgood** [comment]
Corrigido!
