### ISSUE TITLE
Envio via API ou Agendamento não fica no historico 

### ISSUE THREAD

**Issue by rapososoftwares** [ticketz-oss/ticketz#223]
Quando é feito envio via API ou menu de agendamento, a mensagem não fica no historico da conversa.

Exemplo de envio via API para grupo.
![Screenshot_1](https://github.com/user-attachments/assets/b0666b73-d935-44e4-a2a4-33925547b012)
![Screenshot_3](https://github.com/user-attachments/assets/008460b0-2fee-4a2a-970d-519094e9251d)

Envio via Agendamento para um contato
![image](https://github.com/user-attachments/assets/dff41de0-6c95-445b-8e3c-4c775081d123)
![image](https://github.com/user-attachments/assets/8a49d335-21fe-40a8-9adb-96029326cd4a)

**Comment by allgood** [comment]
O problema nessa questão é com relação à existência ou não de tickets abertos no momento do envio... 

1. se já tem um ticket aberto a mensagem é colocada ali, mas se o contato já está falando com o atendente isso pode entrar no meio da conversa

2. se não tem um ticket aberto é necessário criar um

A minha tendência é cuidar da segunda alternativa e não me importar com a primeira.

**Comment by allgood** [comment]
Estou implementando a opção para salvar na conversa a mensagem enviada pelo agendamento.

O salvamento da mensagem enviada via API ainda não está sendo abordado
