### ISSUE TITLE
Fechar/encerrar atendimento de grupo

### ISSUE THREAD

**Issue by leonardooliveira64** [ticketz-oss/ticketz#226]
Ter a opção de encerrar o atendimento em grupos... 
para não ficar todos os grupos "abertos" na aba grupos.
E os encerrados ficar na aba encerrados, assim fica mais organizador visualmente

**Comment by allgood** [comment]
Quando ativada a aba de Grupos eles passam a não serem tratados como ticket de atendimento, portanto não possuem mais o estado "aberto" ou "fechado". Habilitar o comando fechar pode atrapalhar em equipes. Caso deseje tratar grupos como atendimento o ideal é deixar desativada a aba de grupos.
