### ISSUE TITLE
Botão Assinar

### ISSUE THREAD

**Issue by leonardooliveira64** [ticketz-oss/ticketz#239]
Deixar "desmarcar" a flag assinatura apenas para usuario admin, ou colocar uma opção nas configurações para mostrar ou não o campo....

**Comment by allgood** [comment]
@leonardooliveira64 

O botão assinar precisa ficar habilitado para todos por uma razão: as vezes o atendente precisa falar com alguma automação e não funcionará por conta da assinatura.

Fora isso, dentro do sistema todas as mensagens ficam registradas com a autoria, podendo ser auditadas posteriormente para conferir quem foi o emissor de cada uma.
