### ISSUE TITLE
Poder selecionar resposta rápida pelas setas de navegação do teclado.

### ISSUE THREAD

**Issue by danielrvieira** [ticketz-oss/ticketz#240]
Gostaria de deixar uma feature aqui, onde no caso é ao selecionar um atalho com / e abrir a lista de respostas rápidas, poder navegar entre elas usando a seta cima e baixo do teclado, sem precisar selecionar com o mouse.

Daria uma baita ajuda onde diariamente, temos mais de 300 leads entrando em contato, e utilizamos muito as respostas rápidas.

**Comment by allgood** [comment]
Funcionava antes, ocorreu uma regressão por conta da correção do bug #197 

Corrigindo
