### ISSUE TITLE
Maximizar foto do contato

### ISSUE THREAD

**Issue by renan-delgado** [ticketz-oss/ticketz#242]
seria valioso que a foto do contato fosse maximizada ao clicar nela...
![image](https://github.com/user-attachments/assets/6e0ad9c3-01d9-4d90-8fd3-404a2ba9d063)
muitas vezes nao sabemos que é.

**Comment by allgood** [comment]
a imagem do banco é pequena, incluí alterações no Ticketz PRO para obter a imagem maior e mostrá-la ao clicar no perfil do ticket aberto
