### ISSUE TITLE
Mudança no envio de imagem via API

### ISSUE THREAD

**Issue by YanBerardinelli** [ticketz-oss/ticketz#245]
Quando enviar uma media via API o campo body é ignorado e quando enviado ao cliente fica o nome da imagem, gostariamos de sugerir que quando enviado uma unica imagem no campo media ele considera-se o body como conteudo da imagem.

Isso possibilitaria o envio de pix qrcode com copia-cola anexado a imagem em texto.

**Comment by allgood** [comment]
Solução encontrada para o envio de múltiplos arquivos com múltiplas mensagens:

o campo "medias" e o campo "body" pode ser repetidos

* Se houverem múltiplos arquivos sem nenhum body, a mensagem será o nome do arquivo (funcionalidade normal até então)
* Se houverem múltiplos arquivos porém só um "body" a mesma mensagem será repetida para todos.
* Se houverem múltiplos arquivos e múltiplos "body", as mensagens serão associadas a cada arquivo seguindo a ordem da declaração.

Funcionalidade exclusiva para o Ticketz PRO
