### ISSUE TITLE
Cadastro de empresas

### ISSUE THREAD

**Issue by robertonfaustino** [ticketz-oss/ticketz#246]
Pessoal, estou começando com o ticketz agora,
minha duvida é: quando eu crio uma empresa nova, como faço o login? pois só consigo cadastrar o email da empresa e nao tem senha.
Seria na parte de usuarios? se for, como vincular eles a empresa cadastrada.
Estou com a v1.0.29 instalada.

**Comment by allgood** [comment]
@robertonfaustino ,

você pode abrir a edição da empresa clicando no ícone do lápis, e então clicar no botão "Usuário"
