### ISSUE TITLE
Mensagem de transferência de filas sendo enviada mesmo estando em branco

### ISSUE THREAD

**Issue by luizp5** [ticketz-oss/ticketz#254]
**Describe the bug**
Ao transferir um usuário de fila, é enviado uma mensagem de transferência mesmo o campo estando vazio/em branco.
Tentei adicionar um espaço no campo *Mensagem de transferência* porem com isso foi enviado para o usuário um balão vazio na mensagem.

**To Reproduce**

1. Go to 'Acessar conexões'
2. Click on 'Ações'
3. Scroll down to 'Campo Mensagem de Transferência'
4. Este banco está em branco e mesmo assim é enviado a mensagem: *Você foi transferido, em breve iremos iniciar seu atendimento.*

**Expected behavior**
Era para enviar uma mensagem apenas se o campo estivesse preenchido com alguma informação. 

**Screenshots**
![Mesmo o campo Mensagem de Transferência estando em branco é enviado mensagem](https://github.com/user-attachments/assets/f8dcd7b8-e785-4bf8-abc5-d04f14fccaae)
![Quando é adicionado um espaço na mensagem ](https://github.com/user-attachments/assets/52d95988-31fa-4bc0-a2cb-46a4dd70018f)

**Comment by allgood** [comment]
Se a mensagem estiver vazia, passa a não ser enviado nada
