### ISSUE TITLE
Não desativa cliente com assinatura vencida

### ISSUE THREAD

**Issue by TecSecret** [ticketz-oss/ticketz#256]
Assinatura de empresas vencidas não estão sendo bloqueado os acessos no ticketz. O cliente continua com acesso.

Exemplo: 
Carência após vencimento:
![image](https://github.com/user-attachments/assets/33dfe0e2-a0bb-4a06-88eb-3eb809f4a1b0)
Clientes continuam ativos
![image](https://github.com/user-attachments/assets/28e5ef9f-dc30-44db-9c7e-1e5ec1bfd390)

**Comment by allgood** [comment]
verifiquei aqui e o erro ocorre apenas pela autenticação por token (usuário já logado), funcionando normalmente o bloqueio na ocasião de passar a senha.

de qualquer forma é um bug e já estou providenciando a correção.
