### ISSUE TITLE
Receber imagens e áudios de visualização única

### ISSUE THREAD

**Issue by ConnectGestor** [ticketz-oss/ticketz#258]
Imagens de visualização única e áudios não estão chegando no sistema.. Open

**Comment by motheks** [comment]
Pelo menos aqui esta sim.
Ajuda bastante o @allgood se voce conseguir falar se e na open ou na pro e se tem algum erro no console do navegador.

**Comment by allgood** [comment]
@ConnectGestor , consegue me dar mais informações? Nos testes que fiz aqui foi entregue normal.

**Comment by allgood** [comment]
Fui investigar mais, o whatsapp mudou e não está mais enviando as informações da mensagem de visualização única pelo protocolo do whatsapp web, por isso não tem mais como obter estas mensagens.

A princípio não tem como corrigir esse bug, vou fechar com "wont fix"
