### ISSUE TITLE
Bug Fila de Atendimento

### ISSUE THREAD

**Issue by afdadias** [ticketz-oss/ticketz#26]
Opa @⁨~Claudemir⁩ fazendo um teste com ticketz e me deparei com isso aqui:

- Criei uma empresa nova 
- ⁠Criei a fila de atendimento 
- ⁠criei a conexão e setei pra fila de atendimento 
- ⁠criei usuário setei a fila de atendimento, permissão de user 
- ⁠ai pro usuário não chega mensagem agora se eu mudo a permissão para admin chega

A conexão sempre inicia a conversa sem fila de atendimento.

Bug com mais de uma fila ou apenas uma fila

**Comment by afdadias** [comment]
@⁨Claudemir⁩ encontrei o que acontecendo tanto da fila quanto das mensagens rápidas não estarem aparecendo para todos. alguma rota está errada para a profile user:

•⁠  ⁠Tanto as filas, quanto as mensagens rápidas mostram para todos admin agora user não, conexão -> não está linkando com user estou verificando a rotas com calma se corrigir ti aviso

**Comment by allgood** [comment]
@afdadias , eu tenho testado tanto como admin como quanto user e as mensagens estão chegando. Você consegue ver se o problema continua ocorrendo para você?

**Comment by Zebutops** [comment]
Tem que lembrar de ir no usuário e atribuir as filas para ele, mesmo com o admin isso é necessário

**Comment by allgood** [comment]
Acredito que esta issue já está resolvida, caso ainda ocorra por favor escreva abaixo com mais detalhes que eu reabro.
