### ISSUE TITLE
Atualização de código

### ISSUE THREAD

**Issue by VitorHugoVH** [ticketz-oss/ticketz#27]
**Describe the bug**
Não sei como faço para salvar as alterações que fiz no código usando o Docker, ja tentei usar o comando: docker compose -f docker-compose-local.yaml up -d para rodar o código e funciona, porém quando faço alguma alteração não atualiza na Web instantaneamente. Já tentei usar o devcontainers, mas o código não atualiza.

**Comment by rafacsdev** [comment]
Faz o down do docker e depois faz o build
sudo docker compose -f docker-compose-acme.yaml down

sudo docker compose -f docker-compose-acme.yaml up --build -d

**Comment by allgood** [comment]
Docker é utilizado para deploy.

Alterações no código exigem gerar novamente as imagens dos conteiners, com o código atual isso pode ser feito adicionando `--build` ao final do comando up.
