### ISSUE TITLE
Respostas Rapidas

### ISSUE THREAD

**Issue by renan-delgado** [ticketz-oss/ticketz#28]
As respostas rápidas que são criadas não aparecem para os demais usuários.

**Comment by motheks** [comment]
As respostas únicas são por usuarios, pelo menos aqui para nos e nos outros sistemas que ja usamos.

**Comment by EduardoCassemiroCWB** [comment]
Em testes o ideal para gestão é ser concentrada a criação para que todos tenham o mesmo padrão, após a alteração para essa forma de ação, alguns usuários comentaram ter preferencia por esta abordagem, fornecemos um manual de como fazer e algumas frases "mais comuns" para o pessoal iniciar e deu certo.
