### ISSUE TITLE
Recompilar o frontend / Recompile the frontend

### ISSUE THREAD

**Issue by caiot5** [ticketz-oss/ticketz#29]
Como recompilar o frontend nessa sua modificação do whaticket?

----

How to recompile the frontend in your modified whaticket ?

**Comment by allgood** [comment]
Você deve executar o comando down e depois repetir o comando up adicionando o parâmetro --build

Exemplo para uso local:

```bash
docker compose -f docker-compose-local.yaml down
docker compose -f docker-compose-local.yaml up -d --build
```
