### ISSUE TITLE
Tela do agendamento branca

### ISSUE THREAD

**Issue by bentinx** [ticketz-oss/ticketz#31]
![photo_5017508626755071055_y](https://github.com/ticketz-oss/ticketz/assets/166221245/83b31604-fb95-41aa-9e60-7a8aaf64a325)

Para reproduzir basta ir em agendamentos, criar novo agendamento, e clicar em salvar. A tela fica branca e apresenta isso.

**Comment by chironhudo** [comment]
Aqui é semelhante, a tela fica branca. Segue o erro:
`3.30ed77bc.chunk.js:2 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
p @ 3.30ed77bc.chunk.js:2
init @ 3.30ed77bc.chunk.js:2
Howl.init @ 3.30ed77bc.chunk.js:2
a @ 3.30ed77bc.chunk.js:2
(anónimo) @ 2.86d16af6.chunk.js:2
3.30ed77bc.chunk.js:2 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
p @ 3.30ed77bc.chunk.js:2
unload @ 3.30ed77bc.chunk.js:2
_unlockAudio @ 3.30ed77bc.chunk.js:2
init @ 3.30ed77bc.chunk.js:2
Howl.init @ 3.30ed77bc.chunk.js:2
a @ 3.30ed77bc.chunk.js:2
(anónimo) @ 2.86d16af6.chunk.js:2
main.3ca091f3.chunk.js:1 Event:  schedule 
Arg[0]  Object
main.3ca091f3.chunk.js:1 Event:  company-1-schedule 
Arg[0]  {action: 'create', schedule: {…}}
2.86d16af6.chunk.js:2 TypeError: Cannot read properties of undefined (reading 'id')
    at main.3ca091f3.chunk.js:1:346410
    at Array.map (<anonymous>)
    at Am (main.3ca091f3.chunk.js:1:346365)
    at $i (2.86d16af6.chunk.js:2:2229284)
    at Ro (2.86d16af6.chunk.js:2:2238188)
    at mu (2.86d16af6.chunk.js:2:2276926)
    at ls (2.86d16af6.chunk.js:2:2268223)
    at us (2.86d16af6.chunk.js:2:2268148)
    at Ju (2.86d16af6.chunk.js:2:2265157)
    at 2.86d16af6.chunk.js:2:2216542
eu @ 2.86d16af6.chunk.js:2
n.callback @ 2.86d16af6.chunk.js:2
fi @ 2.86d16af6.chunk.js:2
iu @ 2.86d16af6.chunk.js:2
hs @ 2.86d16af6.chunk.js:2
t.unstable_runWithPriority @ 2.86d16af6.chunk.js:2
Ha @ 2.86d16af6.chunk.js:2
ds @ 2.86d16af6.chunk.js:2
Ju @ 2.86d16af6.chunk.js:2
(anónimo) @ 2.86d16af6.chunk.js:2
t.unstable_runWithPriority @ 2.86d16af6.chunk.js:2
Ha @ 2.86d16af6.chunk.js:2
Ya @ 2.86d16af6.chunk.js:2
Va @ 2.86d16af6.chunk.js:2
Gu @ 2.86d16af6.chunk.js:2
go @ 2.86d16af6.chunk.js:2
t @ main.3ca091f3.chunk.js:1
r.emit @ 2.86d16af6.chunk.js:2
emitEvent @ 2.86d16af6.chunk.js:2
onevent @ 2.86d16af6.chunk.js:2
onpacket @ 2.86d16af6.chunk.js:2
r.emit @ 2.86d16af6.chunk.js:2
ondecoded @ 2.86d16af6.chunk.js:2
r.emit @ 2.86d16af6.chunk.js:2
add @ 2.86d16af6.chunk.js:2
ondata @ 2.86d16af6.chunk.js:2
r.emit @ 2.86d16af6.chunk.js:2
onPacket @ 2.86d16af6.chunk.js:2
(anónimo) @ 2.86d16af6.chunk.js:2
r.emit @ 2.86d16af6.chunk.js:2
onPacket @ 2.86d16af6.chunk.js:2
onData @ 2.86d16af6.chunk.js:2
ws.onmessage @ 2.86d16af6.chunk.js:2
2.86d16af6.chunk.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at main.3ca091f3.chunk.js:1:346410
    at Array.map (<anonymous>)
    at Am (main.3ca091f3.chunk.js:1:346365)
    at $i (2.86d16af6.chunk.js:2:2229284)
    at Ro (2.86d16af6.chunk.js:2:2238188)
    at mu (2.86d16af6.chunk.js:2:2276926)
    at ls (2.86d16af6.chunk.js:2:2268223)
    at us (2.86d16af6.chunk.js:2:2268148)
    at Ju (2.86d16af6.chunk.js:2:2265157)
    at 2.86d16af6.chunk.js:2:2216542`
