### ISSUE TITLE
Grupos não apresentam notificação sônara ou visual

### ISSUE THREAD

**Issue by ghost** [ticketz-oss/ticketz#32]
Grupos no ticketz não geram notificação sônara ou visual.

Para reproduzir, o erro criei um grupo e encaminhei varias mensagens no grupo, o grupo abre uma notificação na aba Aguardando, entretanto não gera notificação visual no Windows como os tickets de 1 para 1.

**Comment by caiot5** [comment]
Exato, no whaticket tem o mesmo problema e uma modificação no frontend faz funcionar normalmente mas não consegui fazer essa mesma modificação funcionar no ticketz. Seria bacana alguém com mais conhecimento nessa ferramenta tentar fazer isso e passar o procedimento certo.

**Comment by allgood** [comment]
Marquei como "enhancement" porque embora pareça um bug acredito que foi intencional no código, pois acredito que para ativar isso teria que ter uma opção para silenciar grupos e pessoas, tal como tem no próprio whatsapp.

**Comment by trinityrrocha** [comment]
Realmente a ideia é muito boa, más deve ser estudado o uso de grupos na plataforma, as Grandes empresas de Chatbot pede para que o número do WhatsApp não permaneça em grupos de WhatsApp, talvez seja por consumo de recursos do servidor ou que possa ter algum problema que causa que ainda não sabemos.
![Bot](https://github.com/user-attachments/assets/f80c27d6-98ac-4f35-96a7-2c26ac27397a)

**Comment by allgood** [comment]
@trinityrrocha , na verdade sabemos. Em um grupo cada envio na verdade são muitos envios (um pra cada usuário do grupo), isso faz com que o sistema sofra por conta da natureza monolítica/monoprocessada do nodejs e da forma como a biblioteca baileys está acoplada ao sistema.

**Comment by allgood** [comment]
resolvido já pela nova função de grupos
