### ISSUE TITLE
Filas & Chatbot em loop

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#35]
Mesmo após atualizações o erro continua em relação ao chatbot.

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/eaf752f1-2c9e-424a-a9d4-9df33d654e05)

Não consegue acessar a opção desejada.

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/1805a806-2ae1-4f6d-9a1a-fdd47fa8d705)

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/985f67f0-ca64-422e-8adb-a22923de96a5)

**Comment by allgood** [comment]
corrigido nos últimos commits. Agora é possível configurar opções de saída do chatbot e encaminhamento para outra fila.
