### ISSUE TITLE
Deletar ticket faz consulta desnecessária

### ISSUE THREAD

**Issue by digaovaa** [ticketz-oss/ticketz#36]
No ticketController tem a função remove e nela tem um await showTicketService que só consome recursos de banco, no meu ver é desnecessário

**Comment by allgood** [comment]
@digaovaa ... não é o jeito certo mas aquela consulta serve para checar se o ticket é da mesma empresa que o usuário que está solicitando. Remover essa linha irá permitir que qualquer usuário apague qualquer ticket, inclusive de outra empresa!

A checagem de permissão nos endpoints de Ticket precisa ser reformulada.

**Comment by digaovaa** [comment]
Mas aí não seria só pegar o companyId do usuário que solicitou e passar junto no delete e se não for da company, não deleta. Melhor que fazre uma consulta do tamanho do showticketService... 

E do jeito que está, se vc deletou uma conexão que tinha ticket, e depois vai querer deletar o ticket, não vai deixar por causa dessa consulta.

**Comment by allgood** [comment]
Pode ser, ainda não revisei essa parte, estou fazendo várias checagens e essa mesmo é uma que merece muita atenção com relação às permissões. Fechei a issue porque isso vai ser tratado quando eu revisar essa parte.
