### ISSUE TITLE
Contato desconfigurado

### ISSUE THREAD

**Issue by ghost** [ticketz-oss/ticketz#38]
Contato quando é enviado aparece totalmente desconfigurado e sem funcionalidades no botão.

![image](https://github.com/ticketz-oss/ticketz/assets/166221245/181fd79c-01d1-4405-a22d-ff59c7a656b6)

Para reproduzir, basta enviar de um numero de WhatsApp um numero de contato para o numero em questão no Ticketz

**Comment by allgood** [comment]
Reabrindo... vcards continuam com problema.
