### ISSUE TITLE
Usuário consegue alterar senhas de outros usuários (Título editado)

### ISSUE THREAD

**Issue by EduardoCassemiroCWB** [ticketz-oss/ticketz#39]
**Describe the bug**
Se um usuário souber uma URL pode acessá-la diretamente, exemplo: /users, após acessar consegue alterar a senha de todos os usuários.

a restrição ao dashboard deu certo, imagino que aplicar a mesma regra a toda parte administrativa deva ser suficiente.

**To Reproduce**
Acessar como usuário, alterar a URL.

Teste realizado em localhost (127.0.0.1)

![image](https://github.com/ticketz-oss/ticketz/assets/126513553/838b714c-b35f-484f-b241-a9b6e314f095)

**Comment by allgood** [comment]
O acesso à tela de usuários não é exatamente um problema. O problema é permitir alterar a senha. (Estou alterando o título da issue)

A lista de usuários é disponível a todos da mesma empresa, então se o usuário digitar /users e ver a lista de usuários não representa um problema.

Já ele conseguir alterar dados de outros usuários é um problema!
