### ISSUE TITLE
Tela branca quando há chamada de voz no ticket

### ISSUE THREAD

**Issue by renansteles** [ticketz-oss/ticketz#40]
**Describe the bug**
Está aparecendo tela branca quando tem uma chamada de voz na conversa.

**To Reproduce**
Basta abrir uma conversa em que há uma chamada de voz efetuada ou tentada.

**Comment by allgood** [comment]
Tentei reproduzir o erro aqui e correu tudo bem.

![image](https://github.com/ticketz-oss/ticketz/assets/6070736/3c51d098-567f-4baf-9a19-46909ea6cb24)

Você está utilizando uma versão atualizada do ticketz?

**Comment by renansteles** [comment]
Boa noite Claudemir, deu certo na ultima versão. 

Não estava conseguindo atualizar o projeto pois estava dando problema nas migrations. Mas apaguei tudo e rodei sua ultima versão e deu certo. Obrigado!
