### ISSUE TITLE
Permissão de filas por Grupo (Perfil)

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#43]
Para clientes que lidam com múltiplas filas e diversos usuários, o processo de atribuição de permissões individualmente a cada usuário pode se tornar excessivamente complexo e demorado. Nesse contexto, seria vantajoso desenvolver um sistema no qual diferentes perfis de acesso fossem criados, e as permissões fossem associadas a esses perfis, em vez de serem atribuídas diretamente a cada usuário. Isso simplificaria significativamente a administração das permissões, proporcionando uma abordagem mais eficiente e escalável para gerenciar o acesso aos recursos do sistema.

**Comment by allgood** [comment]
nova função de aba de grupos permite atribuir grupos à filas.
