### ISSUE TITLE
 Erro de  Criar Ticket

### ISSUE THREAD

**Issue by kalbosque** [ticketz-oss/ticketz#45]
Boa tarde ! 

Gostaria de informar que quando um user ou admim vai  Criar Ticket
conseguimos criar mas quando vai enviar a msg  fica em branco no sistema nao aparece a msg mas quando vai olha no celular a msg foi enviada para contato  que foi criando  Ticket mas no sistema fica em branco com nao tivesse registado a msg .

**Comment by allgood** [comment]
Não consegui simular esse erro aqui, favor verificar se ocorre na versão mais recente e detalhar o processo de para replicar a falha.
