### ISSUE TITLE
API does not connect

### ISSUE THREAD

**Issue by agenciahanz** [ticketz-oss/ticketz#51]
The API is not generating the QR code

![prnt](https://github.com/ticketz-oss/ticketz/assets/135042129/5dfba8b4-5317-44c8-9b1e-f04831ec8d33)

**Comment by motheks** [comment]
Tem que atualizar para ultima versão que resolve essa questão!

**Comment by ruither2024** [comment]
> Tem que atualizar para ultima versão que resolve essa questão!

Como fazer, pode me ajudar?

**Comment by allgood** [comment]
### Se você instalou pelo comando de instalação

curl -sSL update.ticke.tz | sudo bash

### Se você instalou via git

```
# encerra serviços
docker compose -f docker-compose-acme.yaml down

# limpa área temporária
git stash clear

# salva alterações na área temporária
git stash

# baixa novo código
git pull

# recupera alterações da área temporária
git stash pop

# reinicia serviços
docker compose -f docker-compose-acme.yaml up -d --build
```

Pode ser que o git stash pop informe que alguma alteração local não foi recuperada indicando em quais arquivos houve conflito, nesse caso deve resolver o conflito no arquivo indicado antes de prosseguir.

**Comment by agenciahanz** [comment]
@allgood Perfeito Funcionou. 
Gostaria de falar contigo sobre o sistema.

**Comment by agenciahanz** [comment]
vou enviar um email.
