### ISSUE TITLE
Possibilidade de gerar protocolo

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#57]
Creio que seria uma melhoria no sistema a opção de ter como ativar protocolo no ticket aberto e quando finalizar ter a opção do operador enviar por email a conversa que foi finalizada.

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/c28f231f-6306-4134-9ff0-90f72f5d91a0)

**Comment by allgood** [comment]
O sistema já gera um número para prococolo bastando colocar {{protocolo}} na mensagem de saudação ou finalização
