### ISSUE TITLE
Tela branca ao deletar Mensagem.

### ISSUE THREAD

**Issue by Mellosre** [ticketz-oss/ticketz#6]
Describe the bug
1 - Ao deletar mensagem ou o cliente delta a mensagem erro de tela branca.
2 - mensagem recebia se for editada só aparece após atualizar o ticket manualmente. F5

To Reproduce

![Captura de Tela 2024-03-15 às 11 40 13](https://github.com/ticketz-oss/ticketz/assets/35300051/504b3265-180f-4796-82e9-100fabf9e09f)
![Captura de Tela 2024-03-15 às 11 39 36](https://github.com/ticketz-oss/ticketz/assets/35300051/7ad48fc3-f480-487b-a13f-bb6b5ecc1e88)
![Captura de Tela 2024-03-15 às 11 38 29](https://github.com/ticketz-oss/ticketz/assets/35300051/45f5376d-d963-4612-b08d-00c01dcbc77a)
![Captura de Tela 2024-03-15 às 11 36 51](https://github.com/ticketz-oss/ticketz/assets/35300051/a82cbb58-7690-440a-9b1d-759499143a88)
![Captura de Tela 2024-03-15 às 11 36 31](https://github.com/ticketz-oss/ticketz/assets/35300051/f7f84994-046c-4209-bc7b-1fb11b09ebb7)
![Captura de Tela 2024-03-15 às 11 35 57](https://github.com/ticketz-oss/ticketz/assets/35300051/6be8c04e-b9ea-4e0e-9996-fd58a6e9e800)

segue os prints de erro ao deletar a mensagem e de mensagem editada pelo cliente só aparece se der F5

**Comment by allgood** [comment]
Acredito que já está resolvido na versão atual.
