### ISSUE TITLE
Busca nao funciona ao dar "Enter"

### ISSUE THREAD

**Issue by renan-delgado** [ticketz-oss/ticketz#60]
a busca não funciona apertando "enter"... é necessário selecionar e deselecionar alguma fila... todos os ticketz finalizados ficam marcado como sem fila também... 

https://github.com/ticketz-oss/ticketz/assets/127997362/79618580-1e09-427f-b6c8-698a6b540361

**Comment by allgood** [comment]
A busca é acionada sem precisar do ENTER, mesmo assim estou fazendo algumas melhorias porque não estava funcionando bem.
