### ISSUE TITLE
Falha no retorno webhook de faturas com planos ajustados

### ISSUE THREAD

**Issue by Livison** [ticketz-oss/ticketz#63]
Quando uma fatura já esta gerada no sistema e é feito qualquer ajuste no plano, o sistema gera o QRCODE para pagamento no valor correto do plano novo na fatura existente, mas não reconhece o pagamento automaticamente quando é feito por pix.

Para reconhecer o pgto, precisa alterar a data do vencimento em 1 dia que seja, para gerar uma nova fatura cujo valor da fatura e do qrcode gerado , sejam iguais. Ai qdo ocorre o pagamento, baixa automaticamente.

**Comment by allgood** [comment]
Tem duas possibilidades de solução:

* Gerar o QR code com o valor do plano e alterar na fatura
* Conferir com o valor do plano

**Comment by allgood** [comment]
Para a correção desse bug eu vou considerar que o que vale é o valor da data do pagamento da fatura, ao alterar o valor do plano o valor de qualquer fatura em aberto do mesmo plano também será alterado.
