### ISSUE TITLE
Titulo da pagina

### ISSUE THREAD

**Issue by Livison** [ticketz-oss/ticketz#64]
O titulo da pagina fica sempre como "ticketz", seria possivel customizar esse titulo na parte do white label?

**Comment by leostrong84** [comment]
Mas no whitelabel tem a opção "Nome do sistema", que justamente muda o nome da página.  Porém o webapp do chrome quando tenta instalar volta para nome e ícone do Ticketz.

**Comment by renan-delgado** [comment]
o whitelabel do ícone também não funciona em webapp

**Comment by allgood** [comment]
duplicado com a #81 - prevalecendo por estar melhor descrito
