### ISSUE TITLE
Erro ao receber edição de mensagem de Android

### ISSUE THREAD

**Issue by cleitonme** [ticketz-oss/ticketz#66]
**Describe the bug**
problemas mensagem editada

envie uma mensagem para numero que esta no ticketz, depois edite ela.. no ticketz so aparece mensagem antes de ser editada.. a mensagem fica assim (desativei mensagens temporárias testar depois daquele nosso outro problema)

![editada](https://github.com/ticketz-oss/ticketz/assets/12551230/03d899ae-1e23-4e90-aa33-5e51c67f9afa)

 - OS: windows
 - Browser chrome
 - Version 125

**Comment by allgood** [comment]
![image](https://github.com/ticketz-oss/ticketz/assets/6070736/9aba7165-e40a-4b69-a272-fb7314805cca)

não consegui simular aqui... consegue conferir se ainda está ocorrendo? Se tiver mais detalhes escreve aqui que eu reabro a issue.

**Comment by allgood** [comment]
Reabrindo e ajustando o título... O problema ocorre quando a mensagem editada vem do celular Android!
