### ISSUE TITLE
Mensagem fora do expediente retornando em horário de expediente 

### ISSUE THREAD

**Issue by ghost** [ticketz-oss/ticketz#74]
Basta citar um horário com a opção de horário habilitada e quando o usuário envia mensagem retorna que está fora do horário de expediente. Mesmo estando dentro do horário.

**Comment by motheks** [comment]
Tem que ver qual horario esta na sua VPS, qual instalação fez a antiga ou simplificada ?

**Comment by mordocks** [comment]
Tambem estou tendo esse erro. instalação simplificada e ja troquei o horario do servidor para o padrão brazil

**Comment by YanBerardinelli** [comment]
estou com o mesmo problema aqui

**Comment by allgood** [comment]
duplicado da #48
