### ISSUE TITLE
Estou fazendo um front mas nao consigo fazer o refresh token

### ISSUE THREAD

**Issue by JoaoPedr0Maciel** [ticketz-oss/ticketz#76]
faço o login e ele seta o token normalmente 
![Captura de tela de 2024-06-03 10-52-33](https://github.com/ticketz-oss/ticketz/assets/146394493/ab5d34f4-2ade-4c86-9782-a534a1339c38)
porem quando eu atualizo a pagina ele da erro 401 no back

**Comment by JoaoPedr0Maciel** [comment]
da pra remover o refresh token do back?

**Comment by allgood** [comment]
não relacionado, dúvidas específicas de desenvolvimento favor utilizar os grupos destinados a isso.

Mesmo assim: o JRT precisa ser fornecido pelo backend, o navegador precisa aceitar ele, você pode estar passando por algum problema relacionado ao CORS.
