### ISSUE TITLE
Visualização de videos

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#84]
Visualizações de vídeos pela plataforma web ou celular, fica cortando metade do vídeo, como se houvesse algum zoom, quando faz download do vídeo mostra correto.

**DOWNLOAD**

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/d53e068d-5d3a-46ae-9016-059e566dcf0a)

**TICKETZ MODO JANELA**

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/6670c30e-29b0-4247-b37b-447c85127130)

**TICKETZ MODO FULL**

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/167823e6-ab79-4574-8912-0d121de9c14f)

**Comment by allgood** [comment]
Resolvida pelo commit 4bd8ca1796ef6289adc7fcfc691110cc7d1f829e
