### ISSUE TITLE
Anexo de imagens no chatbot

### ISSUE THREAD

**Issue by motheks** [ticketz-oss/ticketz#85]
Quando coloco uma imagem dentro de um submenu ele não deixa apagar, não apresenta nenhum erro no console, para resolver tem que apagar a opção inteira.

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/177037f4-f043-4015-931c-8135bd016121)

![image](https://github.com/ticketz-oss/ticketz/assets/66420271/5d750692-fc79-4e9d-93de-4cf8773b9034)

**Comment by allgood** [comment]
Reabrindo... fechada pelo commit errado!
