### ISSUE TITLE
Chat interno

### ISSUE THREAD

**Issue by Wesley-Connect** [ticketz-oss/ticketz#90]
Ao criar um novo chat ele duplica tendo que dar f5 para sumir a duplicata falsa, talves um history.replace após clicar em salvar je resolve... em questão de layout se não tiver seria interessante por no estilizador de cores opções para definir cor dos "balões"de memesgem recebidas e enviadas, no teste fornecido está com uma cor azul muito vibrante e difícil de enxergar..

**Comment by allgood** [comment]
A tela de chat interno ainda vai receber atenção, porém não é foco no momento. Issues de melhoria relacionadas a chat interno por enquanto vão ser fechadas.
