### ISSUE TITLE
recurso "comentários internos"

### ISSUE THREAD

**Issue by gsuee** [ticketz-oss/ticketz#93]
![image](https://github.com/ticketz-oss/ticketz/assets/141363690/d58a9440-1906-4a48-9ef1-0bffea4d8521)

mestre, por favor você pode incluir esta função no projeto, ela serve para deixar um comentário antes de transferir um caso para outro departamento, a fim de atribuir uma tarefa do que fazer ou do que o cliente exige

a opção "Notas privadas"

![image](https://github.com/ticketz-oss/ticketz/assets/141363690/6b1c792d-0143-4bb9-b443-30b3b8b2b951)

![image](https://github.com/ticketz-oss/ticketz/assets/141363690/c66f13b8-23ba-400e-af3c-b8d7d61287b3)

então substitua esta função nos contatos

**Comment by motheks** [comment]
Na PRO ja temos ! @allgood
